### ISSUE TITLE
[v1.1.0] Support theme renderer in uinix-theme

### ISSUE THREAD

**Issue by chrisrzhou** [uinix-js/uinix-theme#2]
## Context
Currently, the theme renderer is left for consumers to implement.  One such implementation is done in `uinix-ui`: https://github.com/uinix-js/uinix-ui/blob/1381d444b6481db4168891b3edff047855de4853/lib/renderer/create-renderer.js

## Advantages
- It will be more convenient to simply support `uinix-ui`'s theme renderer in `uinix-theme`.  Consumers may prefer to implement their own renderers optionally, but this should simplify using just `uinix-theme` for theme-related features.
- Makes `uinix-theme` more useful (since it is currently just a trivial set of utils and theme spec).
- Improves code maintainence of theme rendering related utils (e.g. plugins).
- Simplifies `uinix-ui` to deal purely with integration of a collection primitive components against a UI system (mapping `theme` with `styles`).

## Tasks
- [x] Implement `createThemeRenderer` which returns a theme `renderer`.
  - [x] Implement `renderer.render`.
  - [x] Implement `renderer.renderStaticStyles`.
  - [x] Implement `renderer.renderStyle`.
  - [x] Implement `combineStyles` util (merges and combines fela styles).
- [x] Update tests
- [x] Update types
- [x] Update readme (Intro/Gist, Use, API, Infrastructure).

**Comment by chrisrzhou** [comment]
Resolved in f9039c6fbc985a9e519fc21bc6ca5d606f108d92
